name: Build C++ utility

on:
  push:
    paths:
      - 'src/**/*.cpp'
      - '.github/workflows/*.yml'
  pull_request:
    paths:
      - 'src/**/*.cpp'
  workflow_dispatch:

jobs:
  checkout:
    runs-on: windows-latest
    outputs:
      checkout-path: ${{ steps.upload-artifact.outputs.artifact-path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Upload checkout files as artifact
        uses: actions/upload-artifact@v3
        with:
          name: source
          path: src

  build-msvc:
    runs-on: windows-latest
    needs: checkout

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.13.0
    
    - name: Compile and build source files
      shell: cmd
      run: |
        cl
        cl /std:c++20 /O2 /W4 /LD /EHsc /MD /Fe:src\dlls\api.dll src/api.cpp src/settings.cpp src/asteroids.cpp /link gdi32.lib wininet.lib
        cl /std:c++20 /O2 /W4 /LD /EHsc /MD /Fe:src\dlls\gui.dll src/gui.cpp src/settings.cpp src/asteroids.cpp src/system.cpp src/api.cpp /link gdi32.lib wininet.lib comctl32.lib

    - name: Build docs
      shell: cmd
      run: |
        py src/dieknow.py -docs
        echo "Generated documentation"     

    - name: Commit and push .dll files
      run: |
        git config --global user.name "Ethan Chan"
        git config --global user.email "esamuelchan@gmail.com"
        git add . -f
        git commit -m "Auto-build DLL files using g++" || echo "No changes to commit"
        git push https://$GH_PAT@github.com/eschan145/DieKnow.git main
      env:
        # A GitHub PAT must be set up as an Actions secret in the repository
        GH_PAT: ${{ secrets.GH_PAT }}

  build-gcc:
    runs-on: windows-latest
    needs: checkout

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Compile and build source files
      shell: cmd
      run: |
        dir
        g++ --version
        g++ -O2 -Wextra -shared -std=c++20 -Wmissing-field-initializers -static -o src/dlls/api.dll src/api.cpp src/settings.cpp src/asteroids.cpp -lgdi32 -lwininet
        g++ -O2 -Wextra -Wcast-function-type -Wmissing-field-initializers -shared -std=c++20 -static -o src/dlls/gui.dll src/gui.cpp src/settings.cpp src/asteroids.cpp src/system.cpp src/api.cpp -lgdi32 -lwininet -lcomctl32

  build-clang:
    runs-on: windows-latest
    needs: checkout

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Compile and build source files
      shell: cmd
      run: |
        clang++ --version
        clang++ -O2 -Wextra -shared -std=c++20 -Wmissing-field-initializers -static -o src/dlls/api.dll src/api.cpp src/settings.cpp src/asteroids.cpp -lgdi32 -lwininet
        clang++ -O2 -Wextra -Wcast-function-type -Wmissing-field-initializers -shared -std=c++20 -static -o src/dlls/gui.dll src/gui.cpp src/settings.cpp src/asteroids.cpp src/system.cpp src/api.cpp -lgdi32 -lwininet -lcomctl32

  list-files:
    needs: [build-msvc, build-gcc, build-clang]
    runs-on: windows-latest

    steps:
      - name: Verify DLLs are built
        shell: cmd
        run: |
          ls -l src/dlls/api.dll
          ls -l src/dlls/gui.dll
