name: C++ Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run cpplint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install cpplint
      run: pip install cpplint

    - name: Run cpplint
      run: cpplint --recursive --extensions=h,cpp .
