name: Generate documentation

on:
  push:
    branches:
      - main

jobs:
  run-cmd:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docs
        shell: cmd
        run: |
          py dieknow.py -docs
          echo "Generated documentation"
